pipeline {
    agent any
    environment {
        DB_HOST = '192.15.10.4'
        USERNAME = 'user1'
        PASSWORD = 'passwd122'
        }
    stages {
        stage('Setup') {
            steps {
                
                sh "pip install -r requirements.txt"
                echo "host name : ${DB_HOST}"
            }
                        }
        stage('Test') {
            steps {
                
                sh "pytest"
                echo "user is: ${USERNAME}  password : ${PASSWORD}"
                
            }
        }    
        stage('Deployment') {
            
            steps {
                echo "Running Deployment"
                
            }
        } 
        
    }     
    }